test(fwdctl): parallelize test suite (#1540)
## Why this should be merged

When running `cargo nextest run`, I got errors similar to this:

```
       FAIL [   0.271s] firewood-fwdctl::cli fwdctl_check_db_with_data
  stdout ───

    running 1 test
    test fwdctl_check_db_with_data ... FAILED

    failures:

    failures:
        fwdctl_check_db_with_data

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 12 filtered out; finished in 0.26s
    
  stderr ───
    Seed 18381270355561475035: to rerun with this data, export FIREWOOD_TEST_SEED=18381270355561475035

    thread 'fwdctl_check_db_with_data' (15773074) panicked at /Users/rodrigo.villar/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5:
    Unexpected failure.
    code=1
    stderr=```"Error: FileIO(FileIoError { inner: Custom { kind: WouldBlock, error: \"WouldBlock\" }, filename: Some(\"/Users/rodrigo.villar/go/src/github.com/ava-labs/firewood/target/tmp/firewood.db\"), offset: 0, context: Some(\"unable to obtain advisory lock: database may be opened by another instance\") })\n"```
    command=`"/Users/rodrigo.villar/go/src/github.com/ava-labs/firewood/target/debug/fwdctl" "create" "--db" "/Users/rodrigo.villar/go/src/github.com/ava-labs/firewood/target/tmp"`
    code=1
    stdout=""
    stderr="Error: FileIO(FileIoError { inner: Custom { kind: WouldBlock, error: \"WouldBlock\" }, filename: Some(\"/Users/rodrigo.villar/go/src/github.com/ava-labs/firewood/target/tmp/firewood.db\"), offset: 0, context: Some(\"unable to obtain advisory lock: database may be opened by another instance\") })\n"

    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It appears that `cargo nextest run` doesn't acknowledge the `#[serial]`
attribute and runs the tests in parallel, immediately failing because
our tests rely on the same filepath for creating a Firewood instance.
While this PR favors usage of `cargo nextest`, we should regardless
strive to have independent, isolated tests which this PR achieves.

## How this works

Modifies tests to use their own directory + cleans up some code.

## How this was tested

CI + ran `cargo nextest run`

## Need to be documented in RELEASES.md?

No